### ISSUE TITLE
Not able to load modpack for unlimitedtech

### ISSUE THREAD

**Issue by mentyson** [K1ltu/UnlimitedTech#1]
When attempting to use launcher from curse, it results in a crash. When attempting to use launcher, it will attempt to load and then just stop loading about 2/3 of the way through. I have the crash report from the curse launcher attempt. Not sure what to look for?
[crash-2016-09-14_00.05.44-client.txt](https://github.com/K1ltu/UnlimitedTech/files/475459/crash-2016-09-14_00.05.44-client.txt)

**Comment by LeonPhilips** [comment]
Sorry to hear that.
I took a quick look at your crash report and found this:

> java.lang.OutOfMemoryError: GC overhead limit exceeded

Are you sure you are using the right amount of RAM allocated for the game (And have it available on your pc)

Another option is that you have `java 32 bit` installed, you will need to use `java 64 bit` if you want to allocate more than half a gigabyte of RAM.

You can also use the custom launcher I built here: [https://unlimitedserver.org/](https://unlimitedserver.org/) or via the direct link [here](https://terminator.cf/Public/UnlimitedCraft%20-%20Launcher/UnlimitedCraft%20Launcher%202.1.jar)
Current launcher version is: 2.1

Hope it helps!

**Comment by K1ltu** [comment]
Resolved
