### ISSUE TITLE
Spice of life - Agressive

### ISSUE THREAD

**Issue by LeonPhilips** [K1ltu/UnlimitedTech#2]
The [Spice of life](https://minecraft.curseforge.com/projects/the-spice-of-life) mod seems a bit agressive in diminishing returns. Further insight would be appreciated.

I am also trying to get users to use this `issues` section in github. by posting issues.

**Comment by LeonPhilips** [comment]
Update: Just saw someone starve with 3 types of food in his inventory. _Hilarious_. :poop:

![pic](https://cloud.githubusercontent.com/assets/13693773/18647333/bf05a3c6-7eb5-11e6-8e14-b77891803d0b.png)

**Comment by K1ltu** [comment]
food history reduced to 6
initial bypass extended to 12

Hope it helps.
