### ISSUE TITLE
Quality of life mods

### ISSUE THREAD

**Issue by Imotepchief** [K1ltu/UnlimitedTech#32]
A few mods I would like to see added, just to improve the general quality of the pack.

- Mouse Tweaks
- Hunger Overhaul (mainly for food information)
- Crafting Tweaks (nvm that is only 1.7.10/1.12)
- Just Enough Calculation
- Akashic Tome
- Tomb Many Graves - Replace the Graves mod(which doesn't work well)

Also, it would be awesome if you updated the whole pack to 1.12, as 1.10 is absolute garbage.

**Comment by K1ltu** [comment]
i have added all mods but hunger overhaul and removed gravestone
closing this out now onto osmium.....
