### ISSUE TITLE
Server Update?

### ISSUE THREAD

**Issue by Iomega0318** [K1ltu/UnlimitedTech#40]
Did you forget to push out an update before updating the server? Figured it'd be easier to ask you here than try and reach you on the forums. Noticed the Server finally says V 1.1, and based on the client log I assume many mods got updated haha.. Anyways you can close this out when you see it :)

**Comment by K1ltu** [comment]
Nop no update yet 1.1 has been what we have been on for about a month havent released 1.2 yet still need to tweak some greggy stuff

**Comment by Iomega0318** [comment]
Hmm that's what I thought, I connected last night then it disconnected while I was in the game and haven't been able to get back on lol.. my log says missing mods haha.. even tried to re-download the pack..

**Comment by Iomega0318** [comment]
`[23:04:58] [Netty Client IO #2/INFO] [FML/]: Attempting connection with missing mods [mcp, FML, Forge, AdvancedRocketryCore, appliedenergistics2-core, OpenComputers|Core, <CoFH ASM>, foamfixcore, actuallyadditions, advanced_solar_panels, advancedRocketry, ae2stuff, AkashicTome, AppleCore, appliedenergistics2, architecturecraft, astralsorcery, AutoRegLib, Baubles, bdlib, BiomesOPlenty, bloodarsenal, BloodMagic, bloodmoon, Botania, Chameleon, chisel, chiselsandbits, ChiselsBytes, clienttweaks, CodeChickenCore, CodeChickenLib, ccl-entityhook, cofhcore, cookingforblockheads, cosmeticarmorreworked, craftingitems, ctgui, MineTweaker3, crafttweakerjei, ctm, CustomBackgrounds, custommainmenu, cyberware, earthworks, eleccore, elevatorid, endercore, EnderIO, EnderStorage, EnderZoo, environmentaltech, extrautils2, bigreactors, fastleafdecay, foamfix, forestry, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, gendustry, advgenerators, geneticsreborn, geographicraft, gravisuite, gregtech, guideapi, huds, hungeroverhaul, Waila, immersiveengineering, immersivepetroleum, IC2, infinitylib, inventoryspam, inventorytweaks, ironchest, JEFB, jehc, JEI, jeiintegration, journeymap, jeresources, libVulpes, malisisblocks, malisiscore, malisisdoors, mantle, mcmultipart, Mekanism, MekanismGenerators, MekanismTools, minefactoryreloaded, MineFactoryReloaded|CompatVanilla, modtweaker, moreoverlays, mousetweaks, MrTJPCoreMod, mtlib, Neat, recipehandler, OpenComputers, harvestcraft, pressure, projectred-core, projectred-integration, projectred-transmission, projectred-illumination, quantumflux, railcraft, randomthings, reauth, redstonearsenal, ResourceLoader, roguelike, RTG, simplegenerators, simplyjetpacks, StorageDrawers, tconstruct, theoneprobe, thermaldynamics, thermalexpansion, thermalfoundation, thutcore, thuttech, TickProfiler, tombmanygraves, torchmaster, unlimitedtweaks, valkyrielib, wired, zerocore] at SERVER`

Snippet of what my log gives me.. *sigh*

**Comment by K1ltu** [comment]
not sure why it wont let you in seems like no one else is having connection issues(just tested) so it makes me think your client is borked... try to import the curse zip in multimc see if that works also we did have a issue with the server around [01:10 am Feb 13] where it was down for an hour

**Comment by Iomega0318** [comment]
Hmm interesting, I'll play with it a bit more when I get home and try some more options, there's a post on the forums I started I don't think I'm the only one, but I seem to be the only one that it's constantly an issue for haha.. I did try a fresh mod pack install but I'll run a MC repair tonight after work and test again.. MC hates me..

**Comment by Iomega0318** [comment]
We finally figured out what's causing the issues, it's on the forums:
http://frozensoul.enjin.com/home/m/8362087/article/4723484
