### ISSUE TITLE
Empowering not working

### ISSUE THREAD

**Issue by fonnymunkey** [K1ltu/UnlimitedTech#6]
When attempting to empower items from Actually Additions, the empowering infusion does not start. It seems as though either the infusion is simply broken, or the documentation on how to do it is incomplete. All stands are supplied with power, each 2 blocks away from the empowerer, and it still does not start. I have tested in giving redstone signal to the empowerer and that does not work either.

**Comment by fonnymunkey** [comment]
Update: Recipe that was not working was the Void crystal empowerment using the black dye object, further attempts show that vanilla black ink works, just not black dye, although NEI shows it as a recipe.

**Comment by K1ltu** [comment]
not relevant with version 1.0.0
