### ISSUE TITLE
Door Duplication

### ISSUE THREAD

**Issue by fonnymunkey** [K1ltu/UnlimitedTech#7]
When breaking doors, 2 doors will be dropped instead of one, with both being labeled as (Open). These do not stack with regular doors, but if you place only one, it will still form into a 2 block door, which then can be broken again into 2 (Open) doors. It seems as though it does not register the door multiblock should only drop one. This is not a huge issue but it can be annoying when the different metadata doors start filling inventory.

**Comment by K1ltu** [comment]
not relevant with version 1.0.0
